---
name: ci
on:
  push:
    branches: master
  pull_request:
    branches: master
    type: [opened, synchronized, re-opened]

jobs:
  tslint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Cache npm modules
        uses: actions/cache@v2
        env:
          cache-name: npm-cache
        with:
          # linux npm cache path
          path: ~/.npm
          # define key comprising of cache hit items
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Setup node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm dependancies for ci
        run: npm ci
      - name: tslint
        run: npm run lint
      - name: build
        run: npm run build
